// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChHh0mndv-gujdgYTwdtXRvGGoHwjoFyw',
    appId: '1:656438476901:android:0667a9696806f69790068c',
    messagingSenderId: '656438476901',
    projectId: 'project-res-1e3aa',
    storageBucket: 'project-res-1e3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qXEUKL5-dMrkLGHzZvx-JGq2RsZWMKg',
    appId: '1:656438476901:ios:b0ee5cc92fb2043590068c',
    messagingSenderId: '656438476901',
    projectId: 'project-res-1e3aa',
    storageBucket: 'project-res-1e3aa.appspot.com',
    androidClientId: '656438476901-7jj457v34sgsett3q45frhf9dd1bk247.apps.googleusercontent.com',
    iosClientId: '656438476901-72tslesslmrlouhi13b8msi424ntip4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
